import CountryItemType from "@/components/base/CountryItem/type";
import Germany from "@/assets/images/countries/germany.png";
import UnitedState from "@/assets/images/countries/united.png";
import Brazil from "@/assets/images/countries/brazil.png";
import Iceland from "@/assets/images/countries/iceland.png";
import Afghanistan from "@/assets/images/countries/afghanistan.png";
import Ailand from "@/assets/images/countries/ailand2.png";
import Albani from "@/assets/images/countries/albani.png";
import Alegria from "@/assets/images/countries/alegria.png";

const countries: CountryItemType[] = [
  {
    id: 1,
    name: "Germany",
    slug: "Germany",
    population: "81.770.900",
    region: "Europe",
    capital: "Berlin",
    image: Germany,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 2,
    name: "United State of Amrica",
    slug: "UniteState",
    population: "322.947.000",
    region: "Americas",
    capital: "Washington.D.C.",
    image: UnitedState,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 3,
    name: "Brazil",
    slug: "Brazil",
    population: "206.135.893",
    region: "Americas",
    capital: "Brasila",
    image: Brazil,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 4,
    name: "Iceland",
    slug: "Iceland",
    population: "334.300",
    region: "Europe",
    capital: "Reykjavlk",
    image: Iceland,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 5,
    name: "Afghanistan",
    slug: "Afghanistan",
    population: "27.657.145",
    region: "Asia",
    capital: "Kabul",
    image: Afghanistan,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 6,
    name: "Aland islands",
    slug: "Alandislands",
    population: "28.875",
    region: "Europe",
    capital: "Maniehamn",
    image: Ailand,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 7,
    name: "Albani",
    slug: "Albani",
    population: "2.886.026",
    region: "Europe",
    capital: "Tirana",
    image: Albani,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
  {
    id: 8,
    name: "Alegria",
    slug: "Alegria",
    population: "40.400.000",
    region: "Africa",
    capital: "Algiers",
    image: Alegria,
    borderCountries: ["France", "Germany", "Netherlands"],
    currencies: "Euro",
    Languages: ["Dutch", "French", "Germany"],
    topLevelDomain: ".be",
    nativeName: "Belge",
  },
];

export default countries;
